FROM golang:1.19-alpine

WORKDIR /app

RUN go install github.com/cosmtrek/air@v1.44.0

COPY go.mod go.sum ./
RUN go mod download

COPY . .

CMD ["air", "-build.cmd", "go build -o tmp/main ./api/main.go", "-build.bin", "./tmp/main"]
